const $=s=>document.querySelector(s);let current=0,held=false,busy=false,timers=[],toastTimer;const pictures=['wall.svg','wall2.svg','wall3.svg'];let history=[{image:1,label:'昨天 · 08:30'},{image:2,label:'9 月 10 日 · 08:30'}];function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2300)}function renderHistory(){}function view(i,label){$('#large-photo').src=pictures[i];$('#large-caption').textContent=label;$('#viewer').showModal()}function schedule(){$('#next-time').textContent=held?'将在三天后恢复更新':$('#daily').checked?'明天 '+$('#update-time').value+' 换一组':'自动更新已暂停';$('#hold').textContent=held?'恢复更新':'多留几天'}function generate(first){if(busy)return;busy=true;held=false;timers.forEach(clearTimeout);$('#stage').classList.remove('revealed');$('#waiting').hidden=false;$('#current-image').hidden=true;$('#current-meta').hidden=true;$('#replay').disabled=true;$('#device-status').textContent='客厅照片墙 · 准备中';$('#waiting-title').textContent=first?'正在搭配你的第一面照片墙':'正在搭配下一组照片';$('#waiting-caption').textContent='从熟悉的照片里，找到新的相遇。';$('#wallstate').textContent='等待新画面';if(first)$('.wallframe img').style.opacity='.08';timers.push(setTimeout(()=>{$('#waiting-title').textContent='正在送到照片墙';$('#waiting-caption').textContent='画面准备好了，正在等待屏幕更新。';$('#wallstate').textContent='模拟屏幕刷新中'},2800));timers.push(setTimeout(()=>{if(!first){history.unshift({image:current,label:'刚刚展示过'});current=(current+1)%pictures.length}$('.wallframe img').src=pictures[current];$('.wallframe img').style.opacity='1';$('#wallstate').textContent='模拟回执：新画面已显示';$('#waiting-title').textContent='第一面回忆，已来到你身边。';if(!first)$('#waiting-title').textContent='新的一面，已来到你身边。';$('#waiting-caption').textContent='';$('#device-status').textContent='客厅照片墙 · 已更新'},4600));timers.push(setTimeout(()=>{$('#current-photo').src=pictures[current];$('#waiting').hidden=true;$('#current-image').hidden=false;$('#current-meta').hidden=false;$('#updated-at').textContent='刚刚更新';$('#stage').classList.add('revealed');$('#replay').disabled=false;busy=false;renderHistory();schedule()},6100))}$('#replay').onclick=()=>startFlow();$('#next').onclick=()=>generate(false);$('#current-image').onclick=()=>view(current,'当前展示 · 客厅照片墙');$('#close-viewer').onclick=()=>$('#viewer').close();$('#hold').onclick=()=>{held=!held;schedule();toast(held?'这组照片会多留三天 · 演示':'已恢复更新安排')};$('#walltoggle').onclick=()=>{$('#wallpanel').hidden=!$('#wallpanel').hidden;$('#walltoggle').textContent=$('#wallpanel').hidden?'查看实体屏模拟':'收起实体屏模拟'};$('#settings').onclick=()=>$('#sheet').hidden=false;$('#close-sheet').onclick=()=>$('#sheet').hidden=true;$('#daily').onchange=schedule;$('#update-time').onchange=schedule;document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#sheet').hidden=true});renderHistory();schedule();

let flowStep='welcome',connectionTimer=null,flowTimers=[],flowEpoch=0;
const chosenTopics=new Set();
function frame(eyebrow,title,intro,content){return `<div class="flow-step"><div class="flow-top"><p class="eyebrow">${eyebrow}</p>${flowStep!=='welcome'?'<button class="flow-back" id="flow-back">← 返回</button>':''}</div><h2>${title}</h2><p class="intro">${intro}</p>${content}</div>`}
function drawFlow(step){flowStep=step;const root=$('#onboarding');$('.scroll').scrollTop=0;
if(step==='welcome')root.innerHTML=frame('01 / 相册','让回忆，<br>自然回到生活里。','从你允许访问的照片里，搭配属于你的照片墙。',`<div class="album-art" aria-hidden="true"><span></span><span></span><span></span></div><button class="primary" id="authorize">开始 · 授权相册</button><p class="flow-note">本次为模拟体验，不读取手机相册，不上传照片。</p>`);
if(step==='permission')root.innerHTML=frame('01 / 相册','把哪些回忆，<br>交给照片墙？','你始终可以调整允许访问的范围。',`<div class="permission-box"><h3>允许 Echooo 访问照片？</h3><p>用于整理照片并搭配照片墙。<br>这是模拟权限窗口，不会触发系统授权。</p><button class="primary" id="grant-all">允许访问全部照片（模拟）</button><button class="quiet" id="grant-some">选择部分照片（模拟）</button><button class="quiet" id="deny">暂不允许</button></div>`);
if(step==='device')root.innerHTML=frame('02 / 连接','让回忆，<br>有一个落脚的地方。','给照片墙接上电源，手机放在它附近。',`<div class="device-art" aria-hidden="true"><div>echooo</div></div><div class="device-row"><span>客厅照片墙</span><small id="found">正在寻找附近设备…</small></div><p class="connection-status" id="connection-status">模拟发现设备中</p><button class="primary" id="connect" disabled>正在寻找照片墙…</button><p class="flow-note">演示设备 · 不使用真实蓝牙或局域网连接</p>`);
if(step==='network')root.innerHTML=frame('02 / 连接','让它连上家，<br>回忆就能自己来。','选择照片墙使用的网络。',`<div class="device-art" aria-hidden="true"><div>echooo</div></div><div class="flow-card"><label>Wi-Fi<select id="network"><option>Home · 演示网络</option><option>Echooo Studio · 演示网络</option></select></label><p>演示网络无需密码；正式配网会由设备连接流程处理。</p></div><p class="connection-status" id="connection-status">照片墙已找到，等待连接</p><button class="primary" id="join">连接照片墙</button><button class="quiet" id="simulate-fail">试试连接失败</button>`);
if(step==='preferences')root.innerHTML=frame('03 / 展示设置','什么样的日常，<br>你想多看一点？','不选也没关系，让照片自然搭配。',`<div class="flow-card"><h3>想多看到的内容</h3><div class="topic-buttons">${['亲友的瞬间','毛孩子','出去走走','好好吃饭','山海与风景','生活小细节'].map(t=>`<button data-topic="${t}" aria-pressed="${chosenTopics.has(t)}">${t}</button>`).join('')}</div><p>主题可多选，只表达偏好，不排除其他照片。</p></div><div class="flow-card"><label>每天自动换一组<input type="checkbox" id="flow-daily" ${$('#daily').checked?'checked':''}></label><label id="flow-time-row">更新时间<input type="time" id="flow-time" value="${$('#update-time').value}"></label></div><button class="primary" id="begin">开始我的第一面照片墙</button><p class="flow-note">首次生成、上屏与后续更新均为模拟。</p>`);
const back=$('#flow-back');if(back)back.onclick=()=>{clearTimeout(connectionTimer);drawFlow({permission:'welcome',device:'permission',network:'device',preferences:'network'}[step])};
if(step==='welcome')$('#authorize').onclick=()=>drawFlow('permission');
if(step==='permission'){const grant=()=>drawFlow('device');$('#grant-all').onclick=grant;$('#grant-some').onclick=()=>{toast('已模拟授权部分照片');grant()};$('#deny').onclick=()=>{drawFlow('welcome');toast('未授权相册，可以稍后开始')}}
if(step==='device'){clearTimeout(connectionTimer);connectionTimer=setTimeout(()=>{if(flowStep!=='device')return;$('#found').textContent='已找到 · Echooo';$('#connection-status').textContent='设备已准备好';$('#connect').disabled=false;$('#connect').textContent='连接这面照片墙';$('#connect').onclick=()=>drawFlow('network')},1000)}
if(step==='network'){const join=fail=>{const epoch=flowEpoch;$('#join').disabled=true;$('#simulate-fail').disabled=true;$('#connection-status').textContent='正在连接网络…';connectionTimer=setTimeout(()=>{if(epoch!==flowEpoch||flowStep!=='network')return;if(fail){$('#connection-status').textContent='连接未完成，请检查网络后重试。';$('#join').textContent='重新连接';$('#join').disabled=false;$('#simulate-fail').disabled=false}else{$('#connection-status').textContent='已连接';drawFlow('preferences')}},1500)};$('#join').onclick=()=>join(false);$('#simulate-fail').onclick=()=>join(true)}
if(step==='preferences'){document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{chosenTopics.has(b.dataset.topic)?chosenTopics.delete(b.dataset.topic):chosenTopics.add(b.dataset.topic);b.setAttribute('aria-pressed',chosenTopics.has(b.dataset.topic))});$('#flow-time-row').hidden=!$('#flow-daily').checked;$('#flow-daily').onchange=()=>$('#flow-time-row').hidden=!$('#flow-daily').checked;$('#begin').onclick=()=>{if($('#flow-daily').checked&&!$('#flow-time').value){toast('请选择更新时间');return}$('#daily').checked=$('#flow-daily').checked;$('#update-time').value=$('#flow-time').value||'08:30';root.hidden=true;$('#dashboard').hidden=false;$('#settings').hidden=false;flowStep='complete';generate(true)}}
}
function startFlow(){flowEpoch++;clearTimeout(connectionTimer);timers.forEach(clearTimeout);busy=false;$('#replay').disabled=false;$('#sheet').hidden=true;if($('#viewer').open)$('#viewer').close();$('#onboarding').hidden=false;$('#dashboard').hidden=true;$('#settings').hidden=true;chosenTopics.clear();$('#daily').checked=false;$('#wallstate').textContent='等待首次连接';$('.wallframe img').style.opacity='.08';drawFlow('welcome')}
startFlow();
